# Site Settings
title: Charley M. Wu
email: charleymswu@gmail.com
description: >
  Hi I'm Charley
baseurl: ""
url: "http://localhost:4000"
twitter_username: thecharleywu 
github_username:  charleywu
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM