# Site Settings
title: Charley M. Wu
email: charleymswu@gmail.com
description: >
  Hi I'm Charley
baseurl: ""
url: "http://localhost:4000"
twitter_username: thecharleywu 
github_username:  charleywu
social:
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Charley_Wu2'}
- {icon: 'google-scholar', link: 'https://scholar.google.com/citations?user=1O2hcVgAAAAJ'}
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: markdown
#plugins: ['jekyll-scholar']
#jekyll scholar
scholar:
  style: apa
  locale: en

  sort_by: year
  order: descending
  bibliography_list_tag: ul

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bibtemplate
  bibtex_filters:
    - latex

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

ms:
  - jekyll-font-awesome-sass
font-awesome:
  assets: true