# Site Settings
title: Charley M. Wu
email: charleymswu@gmail.com
description: >
  Hi I'm Charley
baseurl: ""
url: "https://charleywu.github.io"
twitter_username: thecharleywu
github_username:  charleywu

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: markdown
#plugins: ['jekyll-scholar']

#jekyll scholar
scholar:
  style: assets/bibliography/apa.csl
  locale: en

  sort_by: year
  order: descending
  bibliography_list_tag: ul

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bibtemplate
  bibtex_filters:
    - latex


  replace_strings: true
  #join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
gems:
  - jekyll-font-awesome-sass
font-awesome:
  assets: true